/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";

import type { Bank } from "../Bank";

export class Bank__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    USDFooAddress: string,
    _turboVerifierAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Bank> {
    return super.deploy(
      USDFooAddress,
      _turboVerifierAddress,
      overrides || {}
    ) as Promise<Bank>;
  }
  getDeployTransaction(
    USDFooAddress: string,
    _turboVerifierAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(
      USDFooAddress,
      _turboVerifierAddress,
      overrides || {}
    );
  }
  attach(address: string): Bank {
    return super.attach(address) as Bank;
  }
  connect(signer: Signer): Bank__factory {
    return super.connect(signer) as Bank__factory;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Bank {
    return new Contract(address, _abi, signerOrProvider) as Bank;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "USDFooAddress",
        type: "address",
      },
      {
        internalType: "address",
        name: "_turboVerifierAddress",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    name: "lineSuccessfullyCreated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "userId",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "_maximumAllowanceHash",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "_disposedAmountHash",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "_interestRateHash",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "_accruedInterestsHash",
        type: "bytes32",
      },
    ],
    name: "openLineOfCredit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5060405161025a38038061025a83398101604081905261002f916100e5565b600180546001600160a01b0319166001600160a01b03841690811790915560405163140e25ad60e31b8152655af3107a4000600482015263a0712d6890602401600060405180830381600087803b15801561008957600080fd5b505af115801561009d573d6000803e3d6000fd5b5050600280546001600160a01b0319166001600160a01b03949094169390931790925550610118915050565b80516001600160a01b03811681146100e057600080fd5b919050565b600080604083850312156100f857600080fd5b610101836100c9565b915061010f602084016100c9565b90509250929050565b610133806101276000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063ad5cf40d14602d575b600080fd5b603c603836600460c3565b603e565b005b6040805160808101825285815260208082018681528284018681526060840186815260008b815280855286902094518555915160018086019190915590516002850155905160039093019290925591519081527f5e4d03a69cf1c50a722b7d5e89bedbfe6be5b7f382128a0034c622fb2aff3b54910160405180910390a15050505050565b600080600080600060a0868803121560da57600080fd5b50508335956020850135955060408501359460608101359450608001359250905056fea264697066735822122066b30bd606e1ab0b8bec3a67eb73d2e0b1d36e677b35b1c972745603d1048cec64736f6c634300080a0033";
