/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";

import type { PseudoRandomSquadGenerator } from "../PseudoRandomSquadGenerator";

export class PseudoRandomSquadGenerator__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<PseudoRandomSquadGenerator> {
    return super.deploy(overrides || {}) as Promise<PseudoRandomSquadGenerator>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): PseudoRandomSquadGenerator {
    return super.attach(address) as PseudoRandomSquadGenerator;
  }
  connect(signer: Signer): PseudoRandomSquadGenerator__factory {
    return super.connect(signer) as PseudoRandomSquadGenerator__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PseudoRandomSquadGenerator {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as PseudoRandomSquadGenerator;
  }
}

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    name: "PseudoRandomNumbers",
    type: "event",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50603f80601d6000396000f3fe6080604052600080fdfea2646970667358221220597d8da24de7848ae0cebb6fc36314d85e46a6c299b9cbc5842c0faf7ae8bc6f64736f6c63430008070033";
